python main_qm9.py\
    --config-file 'qm9/U0_config.yml' \
    --output-dir 'train_results/qm9/U0' \
    --save-checkpoint \
    --target 7 \
    --data-path 'datasets/qm9' \
    --no-amp \
    --no-model-ema \
    --no-standardize \
    --no-model-ema \
    --load-checkpoint 'train_results/qm9/U0/checkpoint.pth'